Create entities
Tymisko/car-rental pull request #1
Opened 2022-09-20 20:16 UTC by Tymisko

Create entities class based on entity relationship diagram

![CarRental_ERD drawio](https://user-images.githubusercontent.com/43744496/191355932-cc7e21fd-fee8-4530-bef2-aa6cab08be95.png)

2022-09-21 06:16 UTC, maximanek commented
Well personally I prefer putting FK right after PK because when u open table view u can see every relation instantly. 
E.g Vehicle Entity. It has so many fields so when u want to see all it relationships you need to scroll left because it doesnt fit on your screen

2022-09-21 07:17 UTC, janex-PL commented
Apart from what Max has pointed out, you need to review the usage of ForeignKey attribute.

It all comes down to the fact, that there are no navigation properties defined, only their foreign keys.

Add navigation properties to entities and then check out how ForeignKey attribute works: https://www.entityframeworktutorial.net/code-first/foreignkey-dataannotations-attribute-in-code-first.aspx 

By default, if you define navigation properties and foreign keys by following the naming convention
```csharp
public Guid ExampleId {get;set;}
public Example Example {get;set;}
```
then there is no need for the attribute because EF will handle the relationships automatically. But if you want to explicitly define foreign keys, then go ahead 😎

2022-09-21 07:24 UTC, janex-PL requested changes
Apart from what @maximanek has pointed out, you need to review the usage of ForeignKey attribute.

It all comes down to the fact, that there are no navigation properties defined, only their foreign keys.

Add navigation properties to entities and then check out how ForeignKey attribute works: https://www.entityframeworktutorial.net/code-first/foreignkey-dataannotations-attribute-in-code-first.aspx 

By default, if you define navigation properties and foreign keys by following the naming convention
```csharp
public Guid ExampleId {get;set;}
public Example Example {get;set;}
```
then there is no need for the attribute because EF will handle the relationships automatically. But if you want to explicitly define foreign keys, then go ahead 😎

2022-09-21 07:25 UTC, maximanek approved these changes
No new line at the end of file

2022-09-21 07:28 UTC, janex-PL commented
One more thing: put attributes above the properties, not inline ;)

2022-09-21 18:52 UTC, Tymisko commented
Hi

Firstly I would want to thank you for your reviews. I very much appreciate it. 

Thanks to the article that @janex-PL linked I now understand the differences between the `ForeignKey` attribute and the navigation properties. 

I have replaced `ForeignKey` attribute with navigation properties.
Foreign keys are now under primary key thanks to @maximanek. I haven't thought about the table view.

@janex-PL  please for review after the changes I made  :) 

Greetings, 
Janek :)

2022-09-24 10:14 UTC, janex-PL reviewed
You missed Vehicle class, once you've fixed it we can merge and move on ;)

2022-09-24 10:14 UTC, janex-PL commented on src/Domain/Entities/Vehicle.cs
> +public class Vehicle
You missed one class 😅

2022-10-08 11:23 UTC, janex-PL requested changes
Mostly it's just about adding navigation properties right on the start of a project, will most probably make your future work easier :)

2022-10-08 11:23 UTC, janex-PL commented on src/Domain/Entities/Accessory.cs
> +}
Add here navigation property for Vehicle to define many-to-many relationship explicitly

2022-10-08 11:23 UTC, janex-PL commented on src/Domain/Entities/UserDetails.cs
> +}
I would add a field with type bool which would specify if the details for this user is default.

2022-10-08 11:23 UTC, janex-PL commented on src/Domain/Entities/Brand.cs
> +}
Add navigation property to Model entity

2022-10-08 11:23 UTC, janex-PL commented on src/Domain/Entities/Feature.cs
> +}
Add navigation property to Offer entity

2022-10-08 11:23 UTC, janex-PL commented on src/Domain/Entities/Generation.cs
> +}
Add navigation property to Vehicle entity

2022-10-08 11:23 UTC, janex-PL commented on src/Domain/Entities/Model.cs
> +}
Add navigation property to Generation entity

2022-10-08 11:23 UTC, janex-PL commented on src/Domain/Entities/Offer.cs
> +    public decimal Price { get; set; }
Instead of specyfing one field for price I would make three fields: one for net price, one for tax value and one for gross price (final price)

2022-10-18 18:51 UTC, janex-PL approved these changes
Do the last change mentioned in the review and you can merge ;)

2022-10-18 18:51 UTC, janex-PL commented on src/Domain/Entities/UserDetails.cs
> +    public bool isDefault { get; set; }
Inconsisent naming, change to IsDefault

2022-10-20 03:41 UTC, merged